// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCxMEw0ojrprKP06n3R39hMr3vu3ckhx8',
    appId: '1:593802559816:web:5e1590ef785e90c3e5737d',
    messagingSenderId: '593802559816',
    projectId: 'focusfeed-70ae9',
    authDomain: 'focusfeed-70ae9.firebaseapp.com',
    storageBucket: 'focusfeed-70ae9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxjOJ6BYNyuCLvD12dzdh0s_b4qm67HIQ',
    appId: '1:593802559816:android:433f0058e2721837e5737d',
    messagingSenderId: '593802559816',
    projectId: 'focusfeed-70ae9',
    storageBucket: 'focusfeed-70ae9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6LDFebwNSTsI2sD3IAVzBh4QplShtMHE',
    appId: '1:593802559816:ios:593f760ade9e14b1e5737d',
    messagingSenderId: '593802559816',
    projectId: 'focusfeed-70ae9',
    storageBucket: 'focusfeed-70ae9.firebasestorage.app',
    iosClientId: '593802559816-pr4iedf0u966va8k5rrno2b2531jgt8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusfeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6LDFebwNSTsI2sD3IAVzBh4QplShtMHE',
    appId: '1:593802559816:ios:593f760ade9e14b1e5737d',
    messagingSenderId: '593802559816',
    projectId: 'focusfeed-70ae9',
    storageBucket: 'focusfeed-70ae9.firebasestorage.app',
    iosClientId: '593802559816-pr4iedf0u966va8k5rrno2b2531jgt8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusfeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCxMEw0ojrprKP06n3R39hMr3vu3ckhx8',
    appId: '1:593802559816:web:142009334cf4b452e5737d',
    messagingSenderId: '593802559816',
    projectId: 'focusfeed-70ae9',
    authDomain: 'focusfeed-70ae9.firebaseapp.com',
    storageBucket: 'focusfeed-70ae9.firebasestorage.app',
  );
}
