// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN0PUxgpdbI8b7ku5UIgggAQBR5MrZIno',
    appId: '1:782262276223:web:68a25040e5cec9b298ef4a',
    messagingSenderId: '782262276223',
    projectId: 'pantrypal-ba7d6',
    authDomain: 'pantrypal-ba7d6.firebaseapp.com',
    storageBucket: 'pantrypal-ba7d6.firebasestorage.app',
    measurementId: 'G-30LPT9NS4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPoBcfvhpDBoIVKlqOUwMcVPBGJAGAh5w',
    appId: '1:782262276223:android:0df6ddb54c42ed6298ef4a',
    messagingSenderId: '782262276223',
    projectId: 'pantrypal-ba7d6',
    storageBucket: 'pantrypal-ba7d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCuwK7vAr2hkBNEbNW-0CZh0LT6-7KgpE',
    appId: '1:782262276223:ios:cde88e0eb3895e1998ef4a',
    messagingSenderId: '782262276223',
    projectId: 'pantrypal-ba7d6',
    storageBucket: 'pantrypal-ba7d6.firebasestorage.app',
    iosBundleId: 'com.example.pantrypal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCuwK7vAr2hkBNEbNW-0CZh0LT6-7KgpE',
    appId: '1:782262276223:ios:cde88e0eb3895e1998ef4a',
    messagingSenderId: '782262276223',
    projectId: 'pantrypal-ba7d6',
    storageBucket: 'pantrypal-ba7d6.firebasestorage.app',
    iosBundleId: 'com.example.pantrypal',
  );
}
